//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4918
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090530122919
namespace DAL {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    public class SP {
        
        public static int coop_tb_codfiles_GetAll() {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            return dbi.ExcStoredProcedure("coop_tb_codfiles_GetAll", Keel.SPExcMethod.ExecuteNonQuery);
        }
        
        public static int coop_tb_codsoftitem_GetAll() {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            return dbi.ExcStoredProcedure("coop_tb_codsoftitem_GetAll", Keel.SPExcMethod.ExecuteNonQuery);
        }
        
        public static int coop_tb_user_GetAll() {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            return dbi.ExcStoredProcedure("coop_tb_user_GetAll", Keel.SPExcMethod.ExecuteNonQuery);
        }
        
        public static int coop_tb_codfiles_Insert(string filemd5, string filepath) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "filemd5",
                    "filepath"};
            object[] values = new object[] {
                    filemd5,
                    filepath};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int coop_tb_codfiles_GetOne(string filemd5) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "filemd5"};
            object[] values = new object[] {
                    filemd5};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_GetOne", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int coop_tb_codfiles_Delete(string filemd5) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "filemd5"};
            object[] values = new object[] {
                    filemd5};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_Delete", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int coop_tb_codfiles_Update(string filemd5, string filepath, string PK_filemd5) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "filemd5",
                    "filepath",
                    "PK_filemd5"};
            object[] values = new object[] {
                    filemd5,
                    filepath,
                    PK_filemd5};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codfiles_Insert(string Filemd5, string Filepath) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "Filemd5",
                    "Filepath"};
            object[] values = new object[] {
                    Filemd5,
                    Filepath};
            return dbi.ExcStoredProcedure("SP_Codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codfiles_Update(string Filemd5, string Filepath) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "Filemd5",
                    "Filepath"};
            object[] values = new object[] {
                    Filemd5,
                    Filepath};
            return dbi.ExcStoredProcedure("SP_Codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codfiles_DeleteByPK(string Filemd5) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "Filemd5"};
            object[] values = new object[] {
                    Filemd5};
            return dbi.ExcStoredProcedure("SP_Codfiles_DeleteByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codfiles_SelectAll() {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            return dbi.ExcStoredProcedure("SP_Codfiles_SelectAll", Keel.SPExcMethod.ExecuteNonQuery);
        }
        
        public static int SP_Codfiles_SelectByPK(string Filemd5) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "Filemd5"};
            object[] values = new object[] {
                    Filemd5};
            return dbi.ExcStoredProcedure("SP_Codfiles_SelectByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codfiles_QuickSearch(string searchKey) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "searchKey"};
            object[] values = new object[] {
                    searchKey};
            return dbi.ExcStoredProcedure("SP_Codfiles_QuickSearch", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_Codsoftitem_Insert(string CodFileMd5, string FullName, string SoftName, string Version, int Size, System.DateTime Created, int Score_Good, int Score_Bad, int Money, System.DateTime UploadDateTime, string PhoneTypes, string PhoneOS) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "CodFileMd5",
                    "FullName",
                    "SoftName",
                    "Version",
                    "Size",
                    "Created",
                    "Score_Good",
                    "Score_Bad",
                    "Money",
                    "UploadDateTime",
                    "PhoneTypes",
                    "PhoneOS"};
            object[] values = new object[] {
                    CodFileMd5,
                    FullName,
                    SoftName,
                    Version,
                    Size,
                    Created,
                    Score_Good,
                    Score_Bad,
                    Money,
                    UploadDateTime,
                    PhoneTypes,
                    PhoneOS};
            return dbi.ExcStoredProcedure("SP_Codsoftitem_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int SP_User_Insert(string Username, string Password, string Phonetype, string Email) {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            string[] names = new string[] {
                    "Username",
                    "Password",
                    "Phonetype",
                    "Email"};
            object[] values = new object[] {
                    Username,
                    Password,
                    Phonetype,
                    Email};
            return dbi.ExcStoredProcedure("SP_User_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values);
        }
        
        public static int test1() {
            Keel.SPHelper<int, object> dbi = new Keel.SPHelper<int, object>();
            return dbi.ExcStoredProcedure("test1", Keel.SPExcMethod.ExecuteNonQuery);
        }
    }
}
