'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090516221512
Namespace VBDotNetDemo.Model
    
    <Keel.ORM.DataTableAttribute("tb_codfiles")>  _
    Public Class tb_codfiles
        
        Private var_struct_tb_codfiles As struct_tb_codfiles
        
        '使用空字符串初始化对象
        Public Sub New()
            MyBase.New
            Dim s As String = ""
            Me.var_struct_tb_codfiles = CType(Keel.DB.Common.StringToStruct(s.PadRight(Me.GetLenght, Global.Microsoft.VisualBasic.ChrW(32)), GetType(struct_tb_codfiles)),struct_tb_codfiles)
        End Sub
        
        '使用指定的字符串初始化对象
        Public Sub New(ByVal s As String)
            MyBase.New
            Me.var_struct_tb_codfiles = CType(Keel.DB.Common.StringToStruct(s, GetType(struct_tb_codfiles)),struct_tb_codfiles)
        End Sub
        
        <Keel.ORM.KeyFieldAttribute("filemd5", "String", false)>  _
        Public Property filemd5() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codfiles.ary_filemd5)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codfiles.ary_filemd5 = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(64, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("filepath", "String")>  _
        Public Property filepath() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codfiles.ary_filepath)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codfiles.ary_filepath = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(40, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '将结构转换为字符串
        Public Shadows Function ToString() As String
            Return Keel.DB.Common.StructToString(Me.var_struct_tb_codfiles)
        End Function
        
        '获取以字节为单位的结构总长度
        Public Function GetLenght() As Integer
            Return System.Runtime.InteropServices.Marshal.SizeOf(Me.var_struct_tb_codfiles)
        End Function
    End Class
    
    <System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet:=System.Runtime.InteropServices.CharSet.[Ansi], Pack:=1)>  _
    Public Structure struct_tb_codfiles
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=64)>  _
        Public ary_filemd5() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=40)>  _
        Public ary_filepath() As Byte
    End Structure
End Namespace
