'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090516221512
Namespace VBDotNetDemo.Model
    
    <Keel.ORM.DataTableAttribute("tb_codsoftitem")>  _
    Public Class tb_codsoftitem
        
        Private var_struct_tb_codsoftitem As struct_tb_codsoftitem
        
        '使用空字符串初始化对象
        Public Sub New()
            MyBase.New
            Dim s As String = ""
            Me.var_struct_tb_codsoftitem = CType(Keel.DB.Common.StringToStruct(s.PadRight(Me.GetLenght, Global.Microsoft.VisualBasic.ChrW(32)), GetType(struct_tb_codsoftitem)),struct_tb_codsoftitem)
        End Sub
        
        '使用指定的字符串初始化对象
        Public Sub New(ByVal s As String)
            MyBase.New
            Me.var_struct_tb_codsoftitem = CType(Keel.DB.Common.StringToStruct(s, GetType(struct_tb_codsoftitem)),struct_tb_codsoftitem)
        End Sub
        
        <Keel.ORM.DataFieldAttribute("CodFileMd5", "String")>  _
        Public Property CodFileMd5() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_CodFileMd5)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_CodFileMd5 = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(64, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("FullName", "String")>  _
        Public Property FullName() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_FullName)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_FullName = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("SoftName", "String")>  _
        Public Property SoftName() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_SoftName)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_SoftName = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Version", "String")>  _
        Public Property Version() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Version)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Version = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Size", "Int32")>  _
        Public Property Size() As Integer
            Get
                Return Integer.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Size))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Size = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(10, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Created", "DateTime")>  _
        Public Property Created() As Date
            Get
                Return Date.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Created))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Created = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(23, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Score_Good", "Int32")>  _
        Public Property Score_Good() As Integer
            Get
                Return Integer.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Score_Good))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Score_Good = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(10, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Score_Bad", "Int32")>  _
        Public Property Score_Bad() As Integer
            Get
                Return Integer.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Score_Bad))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Score_Bad = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(10, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Money", "Int32")>  _
        Public Property Money() As Integer
            Get
                Return Integer.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_Money))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_Money = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(10, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("UploadDateTime", "DateTime")>  _
        Public Property UploadDateTime() As Date
            Get
                Return Date.Parse(System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_UploadDateTime))
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_UploadDateTime = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(23, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("PhoneTypes", "String")>  _
        Public Property PhoneTypes() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_PhoneTypes)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_PhoneTypes = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("PhoneOS", "String")>  _
        Public Property PhoneOS() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_codsoftitem.ary_PhoneOS)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_codsoftitem.ary_PhoneOS = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '将结构转换为字符串
        Public Shadows Function ToString() As String
            Return Keel.DB.Common.StructToString(Me.var_struct_tb_codsoftitem)
        End Function
        
        '获取以字节为单位的结构总长度
        Public Function GetLenght() As Integer
            Return System.Runtime.InteropServices.Marshal.SizeOf(Me.var_struct_tb_codsoftitem)
        End Function
    End Class
    
    <System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet:=System.Runtime.InteropServices.CharSet.[Ansi], Pack:=1)>  _
    Public Structure struct_tb_codsoftitem
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=64)>  _
        Public ary_CodFileMd5() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_FullName() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_SoftName() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_Version() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=10)>  _
        Public ary_Size() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=23)>  _
        Public ary_Created() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=10)>  _
        Public ary_Score_Good() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=10)>  _
        Public ary_Score_Bad() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=10)>  _
        Public ary_Money() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=23)>  _
        Public ary_UploadDateTime() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_PhoneTypes() As Byte
        
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_PhoneOS() As Byte
    End Structure
End Namespace
