'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090516221512
Namespace VBDotNetDemo.Model
    
    <Keel.ORM.DataTableAttribute("tb_user")>  _
    Public Class tb_user
        
        Private var_struct_tb_user As struct_tb_user
        
        '使用空字符串初始化对象
        Public Sub New()
            MyBase.New
            Dim s As String = ""
            Me.var_struct_tb_user = CType(Keel.DB.Common.StringToStruct(s.PadRight(Me.GetLenght, Global.Microsoft.VisualBasic.ChrW(32)), GetType(struct_tb_user)),struct_tb_user)
        End Sub
        
        '使用指定的字符串初始化对象
        Public Sub New(ByVal s As String)
            MyBase.New
            Me.var_struct_tb_user = CType(Keel.DB.Common.StringToStruct(s, GetType(struct_tb_user)),struct_tb_user)
        End Sub
        
        '用户名
        <Keel.ORM.DataFieldAttribute("username", "String")>  _
        Public Property username() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_user.ary_username)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_user.ary_username = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '密码
        <Keel.ORM.DataFieldAttribute("password", "String")>  _
        Public Property password() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_user.ary_password)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_user.ary_password = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '手机类型
        <Keel.ORM.DataFieldAttribute("phonetype", "String")>  _
        Public Property phonetype() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_user.ary_phonetype)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_user.ary_phonetype = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '电邮
        <Keel.ORM.DataFieldAttribute("email", "String")>  _
        Public Property email() As String
            Get
                Return System.Text.Encoding.Default.GetString(Me.var_struct_tb_user.ary_email)
            End Get
            Set
                If Object.Equals(value, Nothing) Then
                    Return
                End If
                Me.var_struct_tb_user.ary_email = System.Text.Encoding.Default.GetBytes(value.ToString.PadRight(100, Global.Microsoft.VisualBasic.ChrW(32)))
            End Set
        End Property
        
        '将结构转换为字符串
        Public Shadows Function ToString() As String
            Return Keel.DB.Common.StructToString(Me.var_struct_tb_user)
        End Function
        
        '获取以字节为单位的结构总长度
        Public Function GetLenght() As Integer
            Return System.Runtime.InteropServices.Marshal.SizeOf(Me.var_struct_tb_user)
        End Function
    End Class
    
    <System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet:=System.Runtime.InteropServices.CharSet.[Ansi], Pack:=1)>  _
    Public Structure struct_tb_user
        
        '用户名
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_username() As Byte
        
        '密码
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_password() As Byte
        
        '手机类型
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_phonetype() As Byte
        
        '电邮
        <System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst:=100)>  _
        Public ary_email() As Byte
    End Structure
End Namespace
