//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 此文件由KeelKit自动生成 生成器版本:0.0.0.0
namespace AccessDemo {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("CATEGORY")]
    public class CATEGORY {
        
        private string _CategoryName;
        
        public const string fn_CategoryName = "CategoryName";
        
        private string _ID;
        
        public const string fn_ID = "ID";
        
        // <summary>
        //实例化一个
        //</summary>CATEGORY
        public CATEGORY() {
        }
        
        /// <summary>
        ///实例化一个CATEGORY，并填写所有字段的值
        ///(1个)
        ///</summary>
        public CATEGORY(string param_CategoryName) {
            this.CategoryName = param_CategoryName;
        }
        
        [Keel.ORM.DataFieldAttribute("CategoryName", "StringFixedLength")]
        public string CategoryName {
            get {
                return this._CategoryName;
            }
            set {
                this._CategoryName = value;
            }
        }
        
        [Keel.ORM.KeyFieldAttribute("ID", "StringFixedLength")]
        public string ID {
            get {
                return this._ID;
            }
            set {
                this._ID = value;
            }
        }
    }
}
