//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 此文件由KeelKit自动生成 生成器版本:0.0.0.0
namespace AccessDemo {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("PAPER")]
    public class PAPER {
        
        private string _Category;
        
        public const string fn_Category = "Category";
        
        private System.DateTime _CreateDate;
        
        public const string fn_CreateDate = "CreateDate";
        
        private string _Descript;
        
        public const string fn_Descript = "Descript";
        
        private int _ID;
        
        public const string fn_ID = "ID";
        
        private int _Level;
        
        public const string fn_Level = "Level";
        
        private string _PaperName;
        
        public const string fn_PaperName = "PaperName";
        
        private int _State;
        
        public const string fn_State = "State";
        
        private int _totalScore;
        
        public const string fn_totalScore = "totalScore";
        
        private int _totalTime;
        
        public const string fn_totalTime = "totalTime";
        
        // <summary>
        //实例化一个
        //</summary>PAPER
        public PAPER() {
        }
        
        /// <summary>
        ///实例化一个PAPER，并填写所有字段的值
        ///(8个)
        ///</summary>
        public PAPER(string param_Category, System.DateTime param_CreateDate, string param_Descript, int param_Level, string param_PaperName, int param_State, int param_totalScore, int param_totalTime) {
            this.Category = param_Category;
            this.CreateDate = param_CreateDate;
            this.Descript = param_Descript;
            this.Level = param_Level;
            this.PaperName = param_PaperName;
            this.State = param_State;
            this.totalScore = param_totalScore;
            this.totalTime = param_totalTime;
        }
        
        /// <summary>
        ///实例化一个PAPER，并填写所有必填字段个的值
        ///(共1)
        ///</summary>
        public PAPER(string param_PaperName) {
            this.PaperName = param_PaperName;
        }
        
        [Keel.ORM.DataFieldAttribute("Category", "StringFixedLength")]
        public string Category {
            get {
                return this._Category;
            }
            set {
                this._Category = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CreateDate", "DateTime")]
        public System.DateTime CreateDate {
            get {
                return this._CreateDate;
            }
            set {
                this._CreateDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Descript", "StringFixedLength")]
        public string Descript {
            get {
                return this._Descript;
            }
            set {
                this._Descript = value;
            }
        }
        
        [Keel.ORM.KeyFieldAttribute("ID", "Int32")]
        public int ID {
            get {
                return this._ID;
            }
            set {
                this._ID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Level", "Int32")]
        public int Level {
            get {
                return this._Level;
            }
            set {
                this._Level = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("PaperName", "StringFixedLength")]
        public string PaperName {
            get {
                return this._PaperName;
            }
            set {
                this._PaperName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("State", "Int32")]
        public int State {
            get {
                return this._State;
            }
            set {
                this._State = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("totalScore", "Int32")]
        public int totalScore {
            get {
                return this._totalScore;
            }
            set {
                this._totalScore = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("totalTime", "Int32")]
        public int totalTime {
            get {
                return this._totalTime;
            }
            set {
                this._totalTime = value;
            }
        }
    }
}
