//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090623002115
// KeelKit版本:1.0.3500.25185
namespace WebApplication1 {
    
    
    public partial class ctl_Table_1_Keel {
        
        /// <summary>
        /// keelctl_dec_id 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_id;
        
        /// <summary>
        /// keelctl_dte_sdf 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dte_sdf;
        
        /// <summary>
        /// keelctl_chk_b 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.CheckBox keelctl_chk_b;
        
        /// <summary>
        /// keelctl_dec_sd 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_sd;
        
        /// <summary>
        /// keelctl_txt_dsf 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_dsf;
        
        /// <summary>
        /// keelctl_txt_sfd 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_sfd;
    }
}
