//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090623002118
// KeelKit版本:1.0.3500.25185
namespace WebApplication1 {
    
    
    public partial class ctl_tb_codsoftitem_Keel {
        
        /// <summary>
        /// keelctl_txt_CodFileMd5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_CodFileMd5;
        
        /// <summary>
        /// keelctl_txt_FullName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_FullName;
        
        /// <summary>
        /// keelctl_txt_SoftName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_SoftName;
        
        /// <summary>
        /// keelctl_txt_Version 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_Version;
        
        /// <summary>
        /// keelctl_dec_Size 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_Size;
        
        /// <summary>
        /// keelctl_dte_Created 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dte_Created;
        
        /// <summary>
        /// keelctl_dec_Score_Good 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_Score_Good;
        
        /// <summary>
        /// keelctl_dec_Score_Bad 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_Score_Bad;
        
        /// <summary>
        /// keelctl_dec_Money 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dec_Money;
        
        /// <summary>
        /// keelctl_dte_UploadDateTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_dte_UploadDateTime;
        
        /// <summary>
        /// keelctl_txt_PhoneTypes 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_PhoneTypes;
        
        /// <summary>
        /// keelctl_txt_PhoneOS 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox keelctl_txt_PhoneOS;
    }
}
