//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 此文件由KeelKit自动生成 生成器版本:0.0.0.0 生成日期:20100524122539
namespace WindowsFormsApplication2 {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("images")]
    [System.SerializableAttribute()]
    public class images {
        
        private int _id;
        
        public const string fn_id = "id";
        
        private string _title;
        
        public const string fn_title = "title";
        
        private string _src;
        
        public const string fn_src = "src";
        
        private string _url;
        
        public const string fn_url = "url";
        
        private string _keyword;
        
        public const string fn_keyword = "keyword";
        
        private int _click;
        
        public const string fn_click = "click";
        
        // <summary>
        //实例化一个
        //</summary>images
        public images() {
        }
        
        /// <summary>
        ///实例化一个images，并填写所有字段的值
        ///(5个)
        ///</summary>
        public images(string param_title, string param_src, string param_url, string param_keyword, int param_click) {
            this.title = param_title;
            this.src = param_src;
            this.url = param_url;
            this.keyword = param_keyword;
            this.click = param_click;
        }
        
        /// <summary>
        ///实例化一个images，并填写所有必填字段个的值
        ///(共1)
        ///</summary>
        public images(string param_title) {
            this.title = param_title;
        }
        
        [Keel.ORM.KeyFieldAttribute("id", "Int32")]
        public int id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("title", "AnsiString")]
        public string title {
            get {
                return this._title;
            }
            set {
                this._title = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("src", "AnsiString")]
        public string src {
            get {
                return this._src;
            }
            set {
                this._src = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("url", "AnsiString")]
        public string url {
            get {
                return this._url;
            }
            set {
                this._url = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("keyword", "AnsiString")]
        public string keyword {
            get {
                return this._keyword;
            }
            set {
                this._keyword = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("click", "Int32")]
        public int click {
            get {
                return this._click;
            }
            set {
                this._click = value;
            }
        }
    }
}
