//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 此文件由KeelKit自动生成 生成器版本:0.0.0.0 生成日期:20100524122539
namespace WindowsFormsApplication2 {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("sites")]
    [System.SerializableAttribute()]
    public class sites {
        
        private int _id;
        
        public const string fn_id = "id";
        
        private string _title;
        
        public const string fn_title = "title";
        
        private string _url;
        
        public const string fn_url = "url";
        
        private string _keywords;
        
        public const string fn_keywords = "keywords";
        
        private string _description;
        
        public const string fn_description = "description";
        
        private System.DateTime _jointime;
        
        public const string fn_jointime = "jointime";
        
        private int _click;
        
        public const string fn_click = "click";
        
        // <summary>
        //实例化一个
        //</summary>sites
        public sites() {
        }
        
        /// <summary>
        ///实例化一个sites，并填写所有字段的值
        ///(6个)
        ///</summary>
        public sites(string param_title, string param_url, string param_keywords, string param_description, System.DateTime param_jointime, int param_click) {
            this.title = param_title;
            this.url = param_url;
            this.keywords = param_keywords;
            this.description = param_description;
            this.jointime = param_jointime;
            this.click = param_click;
        }
        
        /// <summary>
        ///实例化一个sites，并填写所有必填字段个的值
        ///(共2)
        ///</summary>
        public sites(string param_title, string param_url) {
            this.title = param_title;
            this.url = param_url;
        }
        
        [Keel.ORM.KeyFieldAttribute("id", "Int32")]
        public int id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("title", "AnsiString")]
        public string title {
            get {
                return this._title;
            }
            set {
                this._title = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("url", "AnsiString")]
        public string url {
            get {
                return this._url;
            }
            set {
                this._url = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("keywords", "AnsiString")]
        public string keywords {
            get {
                return this._keywords;
            }
            set {
                this._keywords = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("description", "AnsiString")]
        public string description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("jointime", "DateTime")]
        public System.DateTime jointime {
            get {
                return this._jointime;
            }
            set {
                this._jointime = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("click", "Int32")]
        public int click {
            get {
                return this._click;
            }
            set {
                this._click = value;
            }
        }
    }
}
