#light
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 生成日期:20090516225329
namespace NewFSharpDemo.DAL
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    open System
    open System.Collections.Generic
    open System.ComponentModel
    open System.Data
    open System.Text
    open Keel.ORM
    
    exception ReturnException8a96789625504701b742024bf9de6187 of obj
    exception ReturnNoneException8a96789625504701b742024bf9de6187
    
    type
        
        SP = class
            new() as this =
                {
                }
            static member test1  () =
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                ((dbi.ExcStoredProcedure("test1", Keel.SPExcMethod.ExecuteNonQuery) :> obj) :?> int)
            
            static member SP_User_Insert  (Username:string, Password:string, Phonetype:string, Email:string) =
                let mutable Username = Username
                let mutable Password = Password
                let mutable Phonetype = Phonetype
                let mutable Email = Email
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("Username")); unbox (box ("Password")); unbox (box ("Phonetype")); unbox (box ("Email")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (Username)); unbox (box (Password)); unbox (box (Phonetype)); unbox (box (Email)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_User_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codsoftitem_Insert  (CodFileMd5:string, FullName:string, SoftName:string, Version:string, Size:int, Created:System.DateTime, Score_Good:int, Score_Bad:int, Money:int, UploadDateTime:System.DateTime, PhoneTypes:string, PhoneOS:string) =
                let mutable CodFileMd5 = CodFileMd5
                let mutable FullName = FullName
                let mutable SoftName = SoftName
                let mutable Version = Version
                let mutable Size = Size
                let mutable Created = Created
                let mutable Score_Good = Score_Good
                let mutable Score_Bad = Score_Bad
                let mutable Money = Money
                let mutable UploadDateTime = UploadDateTime
                let mutable PhoneTypes = PhoneTypes
                let mutable PhoneOS = PhoneOS
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("CodFileMd5")); unbox (box ("FullName")); unbox (box ("SoftName")); unbox (box ("Version")); unbox (box ("Size")); unbox (box ("Created")); unbox (box ("Score_Good")); unbox (box ("Score_Bad")); unbox (box ("Money")); unbox (box ("UploadDateTime")); unbox (box ("PhoneTypes")); unbox (box ("PhoneOS")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (CodFileMd5)); unbox (box (FullName)); unbox (box (SoftName)); unbox (box (Version)); unbox (box (Size)); unbox (box (Created)); unbox (box (Score_Good)); unbox (box (Score_Bad)); unbox (box (Money)); unbox (box (UploadDateTime)); unbox (box (PhoneTypes)); unbox (box (PhoneOS)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codsoftitem_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codfiles_QuickSearch  (searchKey:string) =
                let mutable searchKey = searchKey
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("searchKey")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (searchKey)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codfiles_QuickSearch", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codfiles_SelectByPK  (Filemd5:string) =
                let mutable Filemd5 = Filemd5
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("Filemd5")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (Filemd5)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codfiles_SelectByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codfiles_SelectAll  () =
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                ((dbi.ExcStoredProcedure("SP_Codfiles_SelectAll", Keel.SPExcMethod.ExecuteNonQuery) :> obj) :?> int)
            
            static member SP_Codfiles_DeleteByPK  (Filemd5:string) =
                let mutable Filemd5 = Filemd5
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("Filemd5")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (Filemd5)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codfiles_DeleteByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codfiles_Update  (Filemd5:string, Filepath:string) =
                let mutable Filemd5 = Filemd5
                let mutable Filepath = Filepath
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("Filemd5")); unbox (box ("Filepath")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (Filemd5)); unbox (box (Filepath)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member SP_Codfiles_Insert  (Filemd5:string, Filepath:string) =
                let mutable Filemd5 = Filemd5
                let mutable Filepath = Filepath
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("Filemd5")); unbox (box ("Filepath")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (Filemd5)); unbox (box (Filepath)) |] : obj[])
                ((dbi.ExcStoredProcedure("SP_Codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member coop_tb_codfiles_Update  (filemd5:string, filepath:string, PK_filemd5:string) =
                let mutable filemd5 = filemd5
                let mutable filepath = filepath
                let mutable PK_filemd5 = PK_filemd5
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("filemd5")); unbox (box ("filepath")); unbox (box ("PK_filemd5")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (filemd5)); unbox (box (filepath)); unbox (box (PK_filemd5)) |] : obj[])
                ((dbi.ExcStoredProcedure("coop_tb_codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member coop_tb_codfiles_Delete  (filemd5:string) =
                let mutable filemd5 = filemd5
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("filemd5")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (filemd5)) |] : obj[])
                ((dbi.ExcStoredProcedure("coop_tb_codfiles_Delete", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member coop_tb_codfiles_GetOne  (filemd5:string) =
                let mutable filemd5 = filemd5
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("filemd5")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (filemd5)) |] : obj[])
                ((dbi.ExcStoredProcedure("coop_tb_codfiles_GetOne", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member coop_tb_codfiles_Insert  (filemd5:string, filepath:string) =
                let mutable filemd5 = filemd5
                let mutable filepath = filepath
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                let mutable (names:string[]) = ([| unbox (box ("filemd5")); unbox (box ("filepath")) |] : string[])
                let mutable (values:obj[]) = ([| unbox (box (filemd5)); unbox (box (filepath)) |] : obj[])
                ((dbi.ExcStoredProcedure("coop_tb_codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values) :> obj) :?> int)
            
            static member coop_tb_user_GetAll  () =
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                ((dbi.ExcStoredProcedure("coop_tb_user_GetAll", Keel.SPExcMethod.ExecuteNonQuery) :> obj) :?> int)
            
            static member coop_tb_codsoftitem_GetAll  () =
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                ((dbi.ExcStoredProcedure("coop_tb_codsoftitem_GetAll", Keel.SPExcMethod.ExecuteNonQuery) :> obj) :?> int)
            
            static member coop_tb_codfiles_GetAll  () =
                let mutable (dbi:Keel.SPHelper<int, obj>) = new Keel.SPHelper<int, obj>()
                ((dbi.ExcStoredProcedure("coop_tb_codfiles_GetAll", Keel.SPExcMethod.ExecuteNonQuery) :> obj) :?> int)
        end