'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090516222232
Namespace VBDotNetDemo.DAL
    
    Public Class SP
        
        Public Shared Function coop_tb_codfiles_GetAll() As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Return dbi.ExcStoredProcedure("coop_tb_codfiles_GetAll", Keel.SPExcMethod.ExecuteNonQuery)
        End Function
        
        Public Shared Function coop_tb_codsoftitem_GetAll() As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Return dbi.ExcStoredProcedure("coop_tb_codsoftitem_GetAll", Keel.SPExcMethod.ExecuteNonQuery)
        End Function
        
        Public Shared Function coop_tb_user_GetAll() As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Return dbi.ExcStoredProcedure("coop_tb_user_GetAll", Keel.SPExcMethod.ExecuteNonQuery)
        End Function
        
        Public Shared Function coop_tb_codfiles_Insert(ByVal filemd5 As String, ByVal filepath As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"filemd5", "filepath"}
            Dim values() As Object = New Object() {filemd5, filepath}
            Return dbi.ExcStoredProcedure("coop_tb_codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function coop_tb_codfiles_GetOne(ByVal filemd5 As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"filemd5"}
            Dim values() As Object = New Object() {filemd5}
            Return dbi.ExcStoredProcedure("coop_tb_codfiles_GetOne", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function coop_tb_codfiles_Delete(ByVal filemd5 As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"filemd5"}
            Dim values() As Object = New Object() {filemd5}
            Return dbi.ExcStoredProcedure("coop_tb_codfiles_Delete", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function coop_tb_codfiles_Update(ByVal filemd5 As String, ByVal filepath As String, ByVal PK_filemd5 As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"filemd5", "filepath", "PK_filemd5"}
            Dim values() As Object = New Object() {filemd5, filepath, PK_filemd5}
            Return dbi.ExcStoredProcedure("coop_tb_codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codfiles_Insert(ByVal Filemd5 As String, ByVal Filepath As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"Filemd5", "Filepath"}
            Dim values() As Object = New Object() {Filemd5, Filepath}
            Return dbi.ExcStoredProcedure("SP_Codfiles_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codfiles_Update(ByVal Filemd5 As String, ByVal Filepath As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"Filemd5", "Filepath"}
            Dim values() As Object = New Object() {Filemd5, Filepath}
            Return dbi.ExcStoredProcedure("SP_Codfiles_Update", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codfiles_DeleteByPK(ByVal Filemd5 As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"Filemd5"}
            Dim values() As Object = New Object() {Filemd5}
            Return dbi.ExcStoredProcedure("SP_Codfiles_DeleteByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codfiles_SelectAll() As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Return dbi.ExcStoredProcedure("SP_Codfiles_SelectAll", Keel.SPExcMethod.ExecuteNonQuery)
        End Function
        
        Public Shared Function SP_Codfiles_SelectByPK(ByVal Filemd5 As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"Filemd5"}
            Dim values() As Object = New Object() {Filemd5}
            Return dbi.ExcStoredProcedure("SP_Codfiles_SelectByPK", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codfiles_QuickSearch(ByVal searchKey As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"searchKey"}
            Dim values() As Object = New Object() {searchKey}
            Return dbi.ExcStoredProcedure("SP_Codfiles_QuickSearch", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_Codsoftitem_Insert(ByVal CodFileMd5 As String, ByVal FullName As String, ByVal SoftName As String, ByVal Version As String, ByVal Size As Integer, ByVal Created As Date, ByVal Score_Good As Integer, ByVal Score_Bad As Integer, ByVal Money As Integer, ByVal UploadDateTime As Date, ByVal PhoneTypes As String, ByVal PhoneOS As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"CodFileMd5", "FullName", "SoftName", "Version", "Size", "Created", "Score_Good", "Score_Bad", "Money", "UploadDateTime", "PhoneTypes", "PhoneOS"}
            Dim values() As Object = New Object() {CodFileMd5, FullName, SoftName, Version, Size, Created, Score_Good, Score_Bad, Money, UploadDateTime, PhoneTypes, PhoneOS}
            Return dbi.ExcStoredProcedure("SP_Codsoftitem_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function SP_User_Insert(ByVal Username As String, ByVal Password As String, ByVal Phonetype As String, ByVal Email As String) As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Dim names() As String = New String() {"Username", "Password", "Phonetype", "Email"}
            Dim values() As Object = New Object() {Username, Password, Phonetype, Email}
            Return dbi.ExcStoredProcedure("SP_User_Insert", Keel.SPExcMethod.ExecuteNonQuery, names, values)
        End Function
        
        Public Shared Function test1() As Integer
            Dim dbi As Keel.SPHelper(Of Integer, Object) = New Keel.SPHelper(Of Integer, Object)
            Return dbi.ExcStoredProcedure("test1", Keel.SPExcMethod.ExecuteNonQuery)
        End Function
    End Class
End Namespace
