//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090512010009
namespace SP {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    public class SP {
        
        public List<SQL2KDemo.Model.tb_codfiles> coop_tb_codfiles_GetAll() {
            Keel.DBHelper<List<SQL2KDemo.Model.tb_codfiles>> dbi = new Keel.DBHelper<List<SQL2KDemo.Model.tb_codfiles>>();
            return dbi.ExcStoredProcedure("coop_tb_codfiles_GetAll", Keel.SPExcMethod.List);
        }
        
        public System.Data.DataSet coop_tb_codsoftitem_GetAll(out List<System.Data.DataSet> _ListOut_keel) {
            Keel.DBHelper<System.Data.DataSet> dbi = new Keel.DBHelper<System.Data.DataSet>();
            return dbi.ExcStoredProcedure("coop_tb_codsoftitem_GetAll", Keel.SPExcMethod.Fill, out _ListOut_keel);
        }
        
        public int coop_tb_codfiles_Insert(string @filemd5, string @filepath) {
            Keel.DBHelper<int> dbi = new Keel.DBHelper<int>();
            string[] names = new string[] {
                    "@filemd5",
                    "@filepath"};
            object[] values = new object[] {
                    @filemd5,
                    @filepath};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_Insert", Keel.SPExcMethod.ExecuteScalar, names, values);
        }
        
        public SQL2KDemo.Model.tb_codfiles coop_tb_codfiles_GetOne(string @filemd5) {
            Keel.DBHelper<SQL2KDemo.Model.tb_codfiles> dbi = new Keel.DBHelper<SQL2KDemo.Model.tb_codfiles>();
            string[] names = new string[] {
                    "@filemd5"};
            object[] values = new object[] {
                    @filemd5};
            return dbi.ExcStoredProcedure("coop_tb_codfiles_GetOne", Keel.SPExcMethod.Model, names, values);
        }
        
        public int test1() {
            Keel.DBHelper<int> dbi = new Keel.DBHelper<int>();
            return dbi.ExcStoredProcedure("test1", Keel.SPExcMethod.ExecuteNonQuery);
        }
    }
}
