#light
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 生成日期:20090516224845
namespace NewFSharpDemo.Model
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    open System
    open System.Collections.Generic
    open System.ComponentModel
    open System.Data
    open System.Text
    open Keel.ORM
    
    exception ReturnException6d30b1177f6f415ba52116db881d1ce7 of obj
    exception ReturnNoneException6d30b1177f6f415ba52116db881d1ce7
    
    type
        [<Keel.ORM.DataTableAttribute("tb_codsoftitem")>]
        
        tb_codsoftitem = class
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _CodFileMd5:string
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _FullName:string
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _SoftName:string
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Version:string
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Size:int
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Created:System.DateTime
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Score_Good:int
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Score_Bad:int
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _Money:int
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _UploadDateTime:System.DateTime
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _PhoneTypes:string
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _PhoneOS:string
            new() as this =
                {
                }
            
            abstract CodFileMd5 : string with get,set
            [<Keel.ORM.DataFieldAttribute("CodFileMd5", "String")>]
            default this.CodFileMd5
                with get() : string =
                    ((this._CodFileMd5 :> obj) :?> string)
                and set(value:string) : unit =
                    this._CodFileMd5 <- value
            
            
            abstract FullName : string with get,set
            [<Keel.ORM.DataFieldAttribute("FullName", "String")>]
            default this.FullName
                with get() : string =
                    ((this._FullName :> obj) :?> string)
                and set(value:string) : unit =
                    this._FullName <- value
            
            
            abstract SoftName : string with get,set
            [<Keel.ORM.DataFieldAttribute("SoftName", "String")>]
            default this.SoftName
                with get() : string =
                    ((this._SoftName :> obj) :?> string)
                and set(value:string) : unit =
                    this._SoftName <- value
            
            
            abstract Version : string with get,set
            [<Keel.ORM.DataFieldAttribute("Version", "String")>]
            default this.Version
                with get() : string =
                    ((this._Version :> obj) :?> string)
                and set(value:string) : unit =
                    this._Version <- value
            
            
            abstract Size : int with get,set
            [<Keel.ORM.DataFieldAttribute("Size", "Int32")>]
            default this.Size
                with get() : int =
                    ((this._Size :> obj) :?> int)
                and set(value:int) : unit =
                    this._Size <- value
            
            
            abstract Created : System.DateTime with get,set
            [<Keel.ORM.DataFieldAttribute("Created", "DateTime")>]
            default this.Created
                with get() : System.DateTime =
                    ((this._Created :> obj) :?> System.DateTime)
                and set(value:System.DateTime) : unit =
                    this._Created <- value
            
            
            abstract Score_Good : int with get,set
            [<Keel.ORM.DataFieldAttribute("Score_Good", "Int32")>]
            default this.Score_Good
                with get() : int =
                    ((this._Score_Good :> obj) :?> int)
                and set(value:int) : unit =
                    this._Score_Good <- value
            
            
            abstract Score_Bad : int with get,set
            [<Keel.ORM.DataFieldAttribute("Score_Bad", "Int32")>]
            default this.Score_Bad
                with get() : int =
                    ((this._Score_Bad :> obj) :?> int)
                and set(value:int) : unit =
                    this._Score_Bad <- value
            
            
            abstract Money : int with get,set
            [<Keel.ORM.DataFieldAttribute("Money", "Int32")>]
            default this.Money
                with get() : int =
                    ((this._Money :> obj) :?> int)
                and set(value:int) : unit =
                    this._Money <- value
            
            
            abstract UploadDateTime : System.DateTime with get,set
            [<Keel.ORM.DataFieldAttribute("UploadDateTime", "DateTime")>]
            default this.UploadDateTime
                with get() : System.DateTime =
                    ((this._UploadDateTime :> obj) :?> System.DateTime)
                and set(value:System.DateTime) : unit =
                    this._UploadDateTime <- value
            
            
            abstract PhoneTypes : string with get,set
            [<Keel.ORM.DataFieldAttribute("PhoneTypes", "String")>]
            default this.PhoneTypes
                with get() : string =
                    ((this._PhoneTypes :> obj) :?> string)
                and set(value:string) : unit =
                    this._PhoneTypes <- value
            
            
            abstract PhoneOS : string with get,set
            [<Keel.ORM.DataFieldAttribute("PhoneOS", "String")>]
            default this.PhoneOS
                with get() : string =
                    ((this._PhoneOS :> obj) :?> string)
                and set(value:string) : unit =
                    this._PhoneOS <- value
        end