#light
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 生成日期:20090516224843
namespace NewFSharpDemo.Model
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    open System
    open System.Collections.Generic
    open System.ComponentModel
    open System.Data
    open System.Text
    open Keel.ORM
    
    exception ReturnException6b172adbc97a490a826a2b2f7d74940a of obj
    exception ReturnNoneException6b172adbc97a490a826a2b2f7d74940a
    
    type
        [<Keel.ORM.DataTableAttribute("tb_user")>]
        
        tb_user = class
            /// <summary>
            /// 用户名
            /// </summary>
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _username:string
            
            /// <summary>
            /// 密码
            /// </summary>
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _password:string
            
            /// <summary>
            /// 手机类型
            /// </summary>
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _phonetype:string
            
            /// <summary>
            /// 电邮
            /// </summary>
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable _email:string
            new() as this =
                {
                }
            /// <summary>
            /// 用户名
            /// </summary>
            
            abstract username : string with get,set
            [<Keel.ORM.DataFieldAttribute("username", "String")>]
            default this.username
                with get() : string =
                    ((this._username :> obj) :?> string)
                and set(value:string) : unit =
                    this._username <- value
            
            /// <summary>
            /// 密码
            /// </summary>
            
            abstract password : string with get,set
            [<Keel.ORM.DataFieldAttribute("password", "String")>]
            default this.password
                with get() : string =
                    ((this._password :> obj) :?> string)
                and set(value:string) : unit =
                    this._password <- value
            
            /// <summary>
            /// 手机类型
            /// </summary>
            
            abstract phonetype : string with get,set
            [<Keel.ORM.DataFieldAttribute("phonetype", "String")>]
            default this.phonetype
                with get() : string =
                    ((this._phonetype :> obj) :?> string)
                and set(value:string) : unit =
                    this._phonetype <- value
            
            /// <summary>
            /// 电邮
            /// </summary>
            
            abstract email : string with get,set
            [<Keel.ORM.DataFieldAttribute("email", "String")>]
            default this.email
                with get() : string =
                    ((this._email :> obj) :?> string)
                and set(value:string) : unit =
                    this._email <- value
        end