'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'生成日期:20090622233624
Namespace WebApplication2
    
    Partial Public Class ctl_tb_codsoftitem_Keel
        
        '''<summary>
        '''keelctl_txt_CodFileMd5 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_CodFileMd5 As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_FullName 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_FullName As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_SoftName 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_SoftName As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_Version 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_Version As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dec_Size 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dec_Size As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dte_Created 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dte_Created As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dec_Score_Good 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dec_Score_Good As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dec_Score_Bad 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dec_Score_Bad As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dec_Money 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dec_Money As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_dte_UploadDateTime 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_dte_UploadDateTime As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_PhoneTypes 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_PhoneTypes As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_PhoneOS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_PhoneOS As System.Web.UI.WebControls.TextBox
    End Class
End Namespace
