'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'生成日期:20090622233623
Namespace WebApplication2
    
    Partial Public Class ctl_tb_codfiles_Keel
        
        '''<summary>
        '''keelctl_txt_filemd5 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_filemd5 As System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''keelctl_txt_filepath 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected keelctl_txt_filepath As System.Web.UI.WebControls.TextBox
    End Class
End Namespace
