//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090524152034
namespace Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("tb_codfiles")]
    public class tb_codfiles {
        
        private string _filemd5;
        
        private string _filepath;
        
        [Keel.ORM.KeyFieldAttribute("filemd5", "String", false)]
        public string filemd5 {
            get {
                return this._filemd5;
            }
            set {
                this._filemd5 = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("filepath", "String")]
        public string filepath {
            get {
                return this._filepath;
            }
            set {
                this._filepath = value;
            }
        }
    }
}
