//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418171643
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataViewAttribute("adsf", "IFNFTEVDVCANCnRfdGFibGVuYW1lICAgICAgPSBDQVNFIFdIRU4gQS5DT0xPUkRFUj0xIFRIRU4gRC5OQ" +
        "U1FIEVMU0UgRC5OQU1FIEVORCwNCnRfdGFibGVkZXNjICAgID0gQ0FTRSBXSEVOIEEuQ09MT1JERVI9M" +
        "SBUSEVOIElTTlVMTChGLlZBTFVFLCcnKSBFTFNFICcnIEVORCwNCnRfZmllbGRpbmRleCAgPSBBLkNPT" +
        "E9SREVSLA0KdF9maWVsZG5hbWUgICAgPSBBLk5BTUUsDQp0X2lkZW50aXR5ICA9IENBU0UgV0hFTiBDT" +
        "0xVTU5QUk9QRVJUWSggQS5JRCxBLk5BTUUsJ0lTSURFTlRJVFknKT0xIFRIRU4gJ6HMJ0VMU0UgJycgR" +
        "U5ELA0KdF90YWJsZWtleSAgICAgID0gQ0FTRSBXSEVOIEVYSVNUUyhTRUxFQ1QgMSBGUk9NIFNZU09CS" +
        "kVDVFMgV0hFUkUgWFRZUEU9J1BLJyBBTkQgUEFSRU5UX09CSj1BLklEIEFORCBOQU1FIElOICgNClNFT" +
        "EVDVCBOQU1FIEZST00gU1lTSU5ERVhFUyBXSEVSRSBJTkRJRCBJTigNClNFTEVDVCBJTkRJRCBGUk9NI" +
        "FNZU0lOREVYS0VZUyBXSEVSRSBJRCA9IEEuSUQgQU5EIENPTElEPUEuQ09MSUQpKSkgVEhFTiAnocwnI" +
        "EVMU0UgJycgRU5ELA0KdF9maWVsZHR5cGUgICAgICA9IEIuTkFNRSwNCnRfZmllbGRiaXRjb3VudCA9I" +
        "EEuTEVOR1RILA0KdF9maWVsZGxlbmdodCAgICAgPSBDT0xVTU5QUk9QRVJUWShBLklELEEuTkFNRSwnU" +
        "FJFQ0lTSU9OJyksDQp0X2ZpZWxkc2NhbGUgID0gSVNOVUxMKENPTFVNTlBST1BFUlRZKEEuSUQsQS5OQ" +
        "U1FLCdTQ0FMRScpLDApLA0KdF9maWVsZGNhbm51bGwgICA9IENBU0UgV0hFTiBBLklTTlVMTEFCTEU9M" +
        "SBUSEVOICehzCdFTFNFICcnIEVORCwNCnRfZmllbGRkZWZhdWx0dmFsdWUgICAgPSBJU05VTEwoRS5UR" +
        "VhULCcnKSwNCnRfZmllbGRkZXNjICA9IElTTlVMTChHLltWQUxVRV0sJycpLA0KdF9maWVsZGlzY29tc" +
        "HV0ZWQgPUNBU0UgV0hFTiBBLklTQ09NUFVURUQ9MSBUSEVOICehzCdFTFNFICcnIEVORA0KRlJPTSANC" +
        "lNZU0NPTFVNTlMgQQ0KTEVGVCBKT0lOIA0KU1lTVFlQRVMgQiANCk9OIA0KQS5YVVNFUlRZUEU9Qi5YV" +
        "VNFUlRZUEUNCklOTkVSIEpPSU4gDQpTWVNPQkpFQ1RTIEQgDQpPTiANCkEuSUQ9RC5JRCAgQU5EIEQuW" +
        "FRZUEU9J1UnIEFORCAgRC5OQU1FPD4nRFRQUk9QRVJUSUVTJw0KTEVGVCBKT0lOIA0KU1lTQ09NTUVOV" +
        "FMgRSANCk9OIA0KQS5DREVGQVVMVD1FLklEDQpMRUZUIEpPSU4gICAgDQpzeXNwcm9wZXJ0aWVzICAgR" +
        "iAgIA0KT04NCmEuaWQgICA9ICAgZi5pZCAgIGFuZCAgIGEuY29saWQgICA9ICAgZi5zbWFsbGlkDQpMR" +
        "UZUIEpPSU4gICAgDQpzeXNwcm9wZXJ0aWVzICAgRyAgIA0KT04NCmQuaWQgICA9ICAgZy5pZCAgIGFuZ" +
        "CAgIGEuY29saWQgICA9ICAgZy5zbWFsbGlkIA0KT1JERVIgQlkgDQpBLklELEEuQ09MT1JERVINCg==")]
    public class adsf {
        
        private string _t_tablename;
        
        private object _t_tabledesc;
        
        private short _t_fieldindex;
        
        private string _t_fieldname;
        
        private string _t_identity;
        
        private string _t_tablekey;
        
        private string _t_fieldtype;
        
        private short _t_fieldbitcount;
        
        private int _t_fieldlenght;
        
        private int _t_fieldscale;
        
        private string _t_fieldcannull;
        
        private string _t_fielddefaultvalue;
        
        private object _t_fielddesc;
        
        private string _t_fieldiscomputed;
        
        [Keel.ORM.DataFieldAttribute("t_tablename")]
        public string t_tablename {
            get {
                return this._t_tablename;
            }
            set {
                this._t_tablename = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_tabledesc")]
        public object t_tabledesc {
            get {
                return this._t_tabledesc;
            }
            set {
                this._t_tabledesc = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldindex")]
        public short t_fieldindex {
            get {
                return this._t_fieldindex;
            }
            set {
                this._t_fieldindex = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldname")]
        public string t_fieldname {
            get {
                return this._t_fieldname;
            }
            set {
                this._t_fieldname = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_identity")]
        public string t_identity {
            get {
                return this._t_identity;
            }
            set {
                this._t_identity = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_tablekey")]
        public string t_tablekey {
            get {
                return this._t_tablekey;
            }
            set {
                this._t_tablekey = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldtype")]
        public string t_fieldtype {
            get {
                return this._t_fieldtype;
            }
            set {
                this._t_fieldtype = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldbitcount")]
        public short t_fieldbitcount {
            get {
                return this._t_fieldbitcount;
            }
            set {
                this._t_fieldbitcount = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldlenght")]
        public int t_fieldlenght {
            get {
                return this._t_fieldlenght;
            }
            set {
                this._t_fieldlenght = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldscale")]
        public int t_fieldscale {
            get {
                return this._t_fieldscale;
            }
            set {
                this._t_fieldscale = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldcannull")]
        public string t_fieldcannull {
            get {
                return this._t_fieldcannull;
            }
            set {
                this._t_fieldcannull = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fielddefaultvalue")]
        public string t_fielddefaultvalue {
            get {
                return this._t_fielddefaultvalue;
            }
            set {
                this._t_fielddefaultvalue = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fielddesc")]
        public object t_fielddesc {
            get {
                return this._t_fielddesc;
            }
            set {
                this._t_fielddesc = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("t_fieldiscomputed")]
        public string t_fieldiscomputed {
            get {
                return this._t_fieldiscomputed;
            }
            set {
                this._t_fieldiscomputed = value;
            }
        }
    }
}
