//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185333
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Categories")]
    public class Categories {
        
        private int _CategoryID;
        
        private string _CategoryName;
        
        private string _Description;
        
        private byte[] _Picture;
        
        [Keel.ORM.KeyFieldAttribute("CategoryID", "Int32")]
        public int CategoryID {
            get {
                return this._CategoryID;
            }
            set {
                this._CategoryID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CategoryName", "String")]
        public string CategoryName {
            get {
                return this._CategoryName;
            }
            set {
                this._CategoryName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Description", "String")]
        public string Description {
            get {
                return this._Description;
            }
            set {
                this._Description = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Picture", "Binary")]
        public byte[] Picture {
            get {
                return this._Picture;
            }
            set {
                this._Picture = value;
            }
        }
    }
}
