//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("CustomerCustomerDemo")]
    public class CustomerCustomerDemo {
        
        private string _CustomerID;
        
        private string _CustomerTypeID;
        
        [Keel.ORM.KeyFieldAttribute("CustomerID", "StringFixedLength", false)]
        public string CustomerID {
            get {
                return this._CustomerID;
            }
            set {
                this._CustomerID = value;
            }
        }
        
        [Keel.ORM.KeyFieldAttribute("CustomerTypeID", "StringFixedLength", false)]
        public string CustomerTypeID {
            get {
                return this._CustomerTypeID;
            }
            set {
                this._CustomerTypeID = value;
            }
        }
    }
}
