//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Customers")]
    public class Customers {
        
        private string _CustomerID;
        
        private string _CompanyName;
        
        private string _ContactName;
        
        private string _ContactTitle;
        
        private string _Address;
        
        private string _City;
        
        private string _Region;
        
        private string _PostalCode;
        
        private string _Country;
        
        private string _Phone;
        
        private string _Fax;
        
        [Keel.ORM.KeyFieldAttribute("CustomerID", "StringFixedLength", false)]
        public string CustomerID {
            get {
                return this._CustomerID;
            }
            set {
                this._CustomerID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CompanyName", "String")]
        public string CompanyName {
            get {
                return this._CompanyName;
            }
            set {
                this._CompanyName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ContactName", "String")]
        public string ContactName {
            get {
                return this._ContactName;
            }
            set {
                this._ContactName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ContactTitle", "String")]
        public string ContactTitle {
            get {
                return this._ContactTitle;
            }
            set {
                this._ContactTitle = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Address", "String")]
        public string Address {
            get {
                return this._Address;
            }
            set {
                this._Address = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("City", "String")]
        public string City {
            get {
                return this._City;
            }
            set {
                this._City = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Region", "String")]
        public string Region {
            get {
                return this._Region;
            }
            set {
                this._Region = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("PostalCode", "String")]
        public string PostalCode {
            get {
                return this._PostalCode;
            }
            set {
                this._PostalCode = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Country", "String")]
        public string Country {
            get {
                return this._Country;
            }
            set {
                this._Country = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Phone", "String")]
        public string Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Fax", "String")]
        public string Fax {
            get {
                return this._Fax;
            }
            set {
                this._Fax = value;
            }
        }
    }
}
