//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418183358
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    /// <summary>
    /// 默认是选择1000条，如果是 sql2k的话会选择前面80行，如果是sql2008,则返回一个错误！
    /// </summary>
    [Keel.ORM.DataViewAttribute("Customers_view", @"U0VMRUNUIFRPUCAxMDAwIFtDdXN0b21lcklEXQ0KICAgICAgLFtDb21wYW55TmFtZV0NCiAgICAgICxbQ29udGFjdE5hbWVdDQogICAgICAsW0NvbnRhY3RUaXRsZV0NCiAgICAgICxbQWRkcmVzc10NCiAgICAgICxbQ2l0eV0NCiAgICAgICxbUmVnaW9uXQ0KICAgICAgLFtQb3N0YWxDb2RlXQ0KICAgICAgLFtDb3VudHJ5XQ0KICAgICAgLFtQaG9uZV0NCiAgICAgICxbRmF4XQ0KICBGUk9NIFtOb3J0aHdpbmRdLltkYm9dLltDdXN0b21lcnNd")]
    [Keel.ORM.DataViewSQL("U0VMRUNUICBTRVJWRVJQUk9QRVJUWSgncHJvZHVjdHZlcnNpb24nKQ==", "OC4wMC4yMDM5", "U0VMRUNUIFRPUCA4MCBbQ3VzdG9tZXJJRF0NCiAgICAgICxbQ29tcGFueU5hbWVdDQogICAgICAsW0NvbnRhY3ROYW1lXQ0KICAgICAgLFtDb250YWN0VGl0bGVdDQogICAgICAsW0FkZHJlc3NdDQogICAgICAsW0NpdHldDQogICAgICAsW1JlZ2lvbl0NCiAgICAgICxbUG9zdGFsQ29kZV0NCiAgICAgICxbQ291bnRyeV0NCiAgICAgICxbUGhvbmVdDQogICAgICAsW0ZheF0NCiAgRlJPTSBbTm9ydGh3aW5kXS5bZGJvXS5bQ3VzdG9tZXJzXQ==")]
    [Keel.ORM.DataViewSQL("U0VMRUNUICBTRVJWRVJQUk9QRVJUWSgncHJvZHVjdHZlcnNpb24nKQ==", "MTAuMC4xNjAwLjIy", "IHNlbGVjdCBmZj1udWxsIA==")]
    public class Customers_view {
        
        private string _CustomerID;
        
        private string _CompanyName;
        
        private string _ContactName;
        
        private string _ContactTitle;
        
        private string _Address;
        
        private string _City;
        
        private string _Region;
        
        private string _PostalCode;
        
        private string _Country;
        
        private string _Phone;
        
        private string _Fax;
        
        [Keel.ORM.DataFieldAttribute("CustomerID")]
        public string CustomerID {
            get {
                return this._CustomerID;
            }
            set {
                this._CustomerID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CompanyName")]
        public string CompanyName {
            get {
                return this._CompanyName;
            }
            set {
                this._CompanyName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ContactName")]
        public string ContactName {
            get {
                return this._ContactName;
            }
            set {
                this._ContactName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ContactTitle")]
        public string ContactTitle {
            get {
                return this._ContactTitle;
            }
            set {
                this._ContactTitle = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Address")]
        public string Address {
            get {
                return this._Address;
            }
            set {
                this._Address = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("City")]
        public string City {
            get {
                return this._City;
            }
            set {
                this._City = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Region")]
        public string Region {
            get {
                return this._Region;
            }
            set {
                this._Region = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("PostalCode")]
        public string PostalCode {
            get {
                return this._PostalCode;
            }
            set {
                this._PostalCode = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Country")]
        public string Country {
            get {
                return this._Country;
            }
            set {
                this._Country = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Phone")]
        public string Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Fax")]
        public string Fax {
            get {
                return this._Fax;
            }
            set {
                this._Fax = value;
            }
        }
    }
}
