//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Employees")]
    public class Employees {
        
        private int _EmployeeID;
        
        private string _LastName;
        
        private string _FirstName;
        
        private string _Title;
        
        private string _TitleOfCourtesy;
        
        private System.DateTime _BirthDate;
        
        private System.DateTime _HireDate;
        
        private string _Address;
        
        private string _City;
        
        private string _Region;
        
        private string _PostalCode;
        
        private string _Country;
        
        private string _HomePhone;
        
        private string _Extension;
        
        private byte[] _Photo;
        
        private string _Notes;
        
        private int _ReportsTo;
        
        private string _PhotoPath;
        
        [Keel.ORM.KeyFieldAttribute("EmployeeID", "Int32")]
        public int EmployeeID {
            get {
                return this._EmployeeID;
            }
            set {
                this._EmployeeID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("LastName", "String")]
        public string LastName {
            get {
                return this._LastName;
            }
            set {
                this._LastName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("FirstName", "String")]
        public string FirstName {
            get {
                return this._FirstName;
            }
            set {
                this._FirstName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Title", "String")]
        public string Title {
            get {
                return this._Title;
            }
            set {
                this._Title = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("TitleOfCourtesy", "String")]
        public string TitleOfCourtesy {
            get {
                return this._TitleOfCourtesy;
            }
            set {
                this._TitleOfCourtesy = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("BirthDate", "DateTime")]
        public System.DateTime BirthDate {
            get {
                return this._BirthDate;
            }
            set {
                this._BirthDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("HireDate", "DateTime")]
        public System.DateTime HireDate {
            get {
                return this._HireDate;
            }
            set {
                this._HireDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Address", "String")]
        public string Address {
            get {
                return this._Address;
            }
            set {
                this._Address = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("City", "String")]
        public string City {
            get {
                return this._City;
            }
            set {
                this._City = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Region", "String")]
        public string Region {
            get {
                return this._Region;
            }
            set {
                this._Region = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("PostalCode", "String")]
        public string PostalCode {
            get {
                return this._PostalCode;
            }
            set {
                this._PostalCode = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Country", "String")]
        public string Country {
            get {
                return this._Country;
            }
            set {
                this._Country = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("HomePhone", "String")]
        public string HomePhone {
            get {
                return this._HomePhone;
            }
            set {
                this._HomePhone = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Extension", "String")]
        public string Extension {
            get {
                return this._Extension;
            }
            set {
                this._Extension = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Photo", "Binary")]
        public byte[] Photo {
            get {
                return this._Photo;
            }
            set {
                this._Photo = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Notes", "String")]
        public string Notes {
            get {
                return this._Notes;
            }
            set {
                this._Notes = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ReportsTo", "Int32")]
        public int ReportsTo {
            get {
                return this._ReportsTo;
            }
            set {
                this._ReportsTo = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("PhotoPath", "String")]
        public string PhotoPath {
            get {
                return this._PhotoPath;
            }
            set {
                this._PhotoPath = value;
            }
        }
    }
}
