//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Orders")]
    public class Orders {
        
        private int _OrderID;
        
        private string _CustomerID;
        
        private int _EmployeeID;
        
        private System.DateTime _OrderDate;
        
        private System.DateTime _RequiredDate;
        
        private System.DateTime _ShippedDate;
        
        private int _ShipVia;
        
        private decimal _Freight;
        
        private string _ShipName;
        
        private string _ShipAddress;
        
        private string _ShipCity;
        
        private string _ShipRegion;
        
        private string _ShipPostalCode;
        
        private string _ShipCountry;
        
        [Keel.ORM.KeyFieldAttribute("OrderID", "Int32")]
        public int OrderID {
            get {
                return this._OrderID;
            }
            set {
                this._OrderID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CustomerID", "StringFixedLength")]
        public string CustomerID {
            get {
                return this._CustomerID;
            }
            set {
                this._CustomerID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("EmployeeID", "Int32")]
        public int EmployeeID {
            get {
                return this._EmployeeID;
            }
            set {
                this._EmployeeID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("OrderDate", "DateTime")]
        public System.DateTime OrderDate {
            get {
                return this._OrderDate;
            }
            set {
                this._OrderDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("RequiredDate", "DateTime")]
        public System.DateTime RequiredDate {
            get {
                return this._RequiredDate;
            }
            set {
                this._RequiredDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShippedDate", "DateTime")]
        public System.DateTime ShippedDate {
            get {
                return this._ShippedDate;
            }
            set {
                this._ShippedDate = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipVia", "Int32")]
        public int ShipVia {
            get {
                return this._ShipVia;
            }
            set {
                this._ShipVia = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Freight", "Currency")]
        public decimal Freight {
            get {
                return this._Freight;
            }
            set {
                this._Freight = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipName", "String")]
        public string ShipName {
            get {
                return this._ShipName;
            }
            set {
                this._ShipName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipAddress", "String")]
        public string ShipAddress {
            get {
                return this._ShipAddress;
            }
            set {
                this._ShipAddress = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipCity", "String")]
        public string ShipCity {
            get {
                return this._ShipCity;
            }
            set {
                this._ShipCity = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipRegion", "String")]
        public string ShipRegion {
            get {
                return this._ShipRegion;
            }
            set {
                this._ShipRegion = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipPostalCode", "String")]
        public string ShipPostalCode {
            get {
                return this._ShipPostalCode;
            }
            set {
                this._ShipPostalCode = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ShipCountry", "String")]
        public string ShipCountry {
            get {
                return this._ShipCountry;
            }
            set {
                this._ShipCountry = value;
            }
        }
    }
}
