//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Order Details")]
    public class Order_Details {
        
        private int _OrderID;
        
        private int _ProductID;
        
        private decimal _UnitPrice;
        
        private short _Quantity;
        
        private float _Discount;
        
        [Keel.ORM.KeyFieldAttribute("OrderID", "Int32", false)]
        public int OrderID {
            get {
                return this._OrderID;
            }
            set {
                this._OrderID = value;
            }
        }
        
        [Keel.ORM.KeyFieldAttribute("ProductID", "Int32", false)]
        public int ProductID {
            get {
                return this._ProductID;
            }
            set {
                this._ProductID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("UnitPrice", "Currency")]
        public decimal UnitPrice {
            get {
                return this._UnitPrice;
            }
            set {
                this._UnitPrice = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Quantity", "Int16")]
        public short Quantity {
            get {
                return this._Quantity;
            }
            set {
                this._Quantity = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Discount", "Single")]
        public float Discount {
            get {
                return this._Discount;
            }
            set {
                this._Discount = value;
            }
        }
    }
}
