//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Products")]
    public class Products {
        
        private int _ProductID;
        
        private string _ProductName;
        
        private int _SupplierID;
        
        private int _CategoryID;
        
        private string _QuantityPerUnit;
        
        private decimal _UnitPrice;
        
        private short _UnitsInStock;
        
        private short _UnitsOnOrder;
        
        private short _ReorderLevel;
        
        private bool _Discontinued;
        
        [Keel.ORM.KeyFieldAttribute("ProductID", "Int32")]
        public int ProductID {
            get {
                return this._ProductID;
            }
            set {
                this._ProductID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ProductName", "String")]
        public string ProductName {
            get {
                return this._ProductName;
            }
            set {
                this._ProductName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("SupplierID", "Int32")]
        public int SupplierID {
            get {
                return this._SupplierID;
            }
            set {
                this._SupplierID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CategoryID", "Int32")]
        public int CategoryID {
            get {
                return this._CategoryID;
            }
            set {
                this._CategoryID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("QuantityPerUnit", "String")]
        public string QuantityPerUnit {
            get {
                return this._QuantityPerUnit;
            }
            set {
                this._QuantityPerUnit = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("UnitPrice", "Currency")]
        public decimal UnitPrice {
            get {
                return this._UnitPrice;
            }
            set {
                this._UnitPrice = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("UnitsInStock", "Int16")]
        public short UnitsInStock {
            get {
                return this._UnitsInStock;
            }
            set {
                this._UnitsInStock = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("UnitsOnOrder", "Int16")]
        public short UnitsOnOrder {
            get {
                return this._UnitsOnOrder;
            }
            set {
                this._UnitsOnOrder = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("ReorderLevel", "Int16")]
        public short ReorderLevel {
            get {
                return this._ReorderLevel;
            }
            set {
                this._ReorderLevel = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Discontinued", "Boolean")]
        public bool Discontinued {
            get {
                return this._Discontinued;
            }
            set {
                this._Discontinued = value;
            }
        }
    }
}
