//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090418185334
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("Shippers")]
    public class Shippers {
        
        private int _ShipperID;
        
        private string _CompanyName;
        
        private string _Phone;
        
        [Keel.ORM.KeyFieldAttribute("ShipperID", "Int32")]
        public int ShipperID {
            get {
                return this._ShipperID;
            }
            set {
                this._ShipperID = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("CompanyName", "String")]
        public string CompanyName {
            get {
                return this._CompanyName;
            }
            set {
                this._CompanyName = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("Phone", "String")]
        public string Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
    }
}
