//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090508100414
namespace SQL2KDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("tb_codfiles")]
    public class tb_codfiles {
        
        private string _filemd5;
        
        private string _filepath;
        
        [Keel.ORM.KeyFieldAttribute("filemd5", "String", false)]
        public string filemd5 {
            get {
                return this._filemd5;
            }
            set {
                this._filemd5 = value;
            }
        }
        
        [Keel.ORM.DataFieldAttribute("filepath", "String")]
        public string filepath {
            get {
                return this._filepath;
            }
            set {
                this._filepath = value;
            }
        }
    }
}
