//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090516210414
namespace NewCSharpDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("tb_codfiles")]
    public class tb_codfiles {
        
        private struct_tb_codfiles var_struct_tb_codfiles;
        
        // 使用空字符串初始化对象
        public tb_codfiles() {
            string s = "";
            this.var_struct_tb_codfiles = ((struct_tb_codfiles)(Keel.DB.Common.StringToStruct(s.PadRight(this.GetLenght(), ' '), typeof(struct_tb_codfiles))));
        }
        
        // 使用指定的字符串初始化对象
        public tb_codfiles(string s) {
            this.var_struct_tb_codfiles = ((struct_tb_codfiles)(Keel.DB.Common.StringToStruct(s, typeof(struct_tb_codfiles))));
        }
        
        [Keel.ORM.KeyFieldAttribute("filemd5", "String", false)]
        public string filemd5 {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_codfiles.ary_filemd5);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_codfiles.ary_filemd5 = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(32, ' '));
            }
        }
        
        [Keel.ORM.DataFieldAttribute("filepath", "String")]
        public string filepath {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_codfiles.ary_filepath);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_codfiles.ary_filepath = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(20, ' '));
            }
        }
        
        // 将结构转换为字符串
        public new string ToString() {
            return Keel.DB.Common.StructToString(this.var_struct_tb_codfiles);
        }
        
        // 获取以字节为单位的结构总长度
        public int GetLenght() {
            return System.Runtime.InteropServices.Marshal.SizeOf(this.var_struct_tb_codfiles);
        }
    }
    
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet=System.Runtime.InteropServices.CharSet.Ansi, Pack=1)]
    public struct struct_tb_codfiles {
        
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=32)]
        public byte[] ary_filemd5;
        
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=20)]
        public byte[] ary_filepath;
    }
}
