//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090516210413
namespace NewCSharpDemo.Model {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    using Keel.ORM;
    
    
    [Keel.ORM.DataTableAttribute("tb_user")]
    public class tb_user {
        
        private struct_tb_user var_struct_tb_user;
        
        // 使用空字符串初始化对象
        public tb_user() {
            string s = "";
            this.var_struct_tb_user = ((struct_tb_user)(Keel.DB.Common.StringToStruct(s.PadRight(this.GetLenght(), ' '), typeof(struct_tb_user))));
        }
        
        // 使用指定的字符串初始化对象
        public tb_user(string s) {
            this.var_struct_tb_user = ((struct_tb_user)(Keel.DB.Common.StringToStruct(s, typeof(struct_tb_user))));
        }
        
        // 用户名
        [Keel.ORM.DataFieldAttribute("username", "String")]
        public string username {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_user.ary_username);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_user.ary_username = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(50, ' '));
            }
        }
        
        // 密码
        [Keel.ORM.DataFieldAttribute("password", "String")]
        public string password {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_user.ary_password);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_user.ary_password = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(50, ' '));
            }
        }
        
        // 手机类型
        [Keel.ORM.DataFieldAttribute("phonetype", "String")]
        public string phonetype {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_user.ary_phonetype);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_user.ary_phonetype = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(50, ' '));
            }
        }
        
        // 电邮
        [Keel.ORM.DataFieldAttribute("email", "String")]
        public string email {
            get {
                return System.Text.Encoding.Default.GetString(this.var_struct_tb_user.ary_email);
            }
            set {
                if (object.Equals(value, null)) {
                    return;
                }
                this.var_struct_tb_user.ary_email = System.Text.Encoding.Default.GetBytes(value.ToString().PadRight(50, ' '));
            }
        }
        
        // 将结构转换为字符串
        public new string ToString() {
            return Keel.DB.Common.StructToString(this.var_struct_tb_user);
        }
        
        // 获取以字节为单位的结构总长度
        public int GetLenght() {
            return System.Runtime.InteropServices.Marshal.SizeOf(this.var_struct_tb_user);
        }
    }
    
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet=System.Runtime.InteropServices.CharSet.Ansi, Pack=1)]
    public struct struct_tb_user {
        
        // 用户名
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=50)]
        public byte[] ary_username;
        
        // 密码
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=50)]
        public byte[] ary_password;
        
        // 手机类型
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=50)]
        public byte[] ary_phonetype;
        
        // 电邮
        [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.ByValArray, SizeConst=50)]
        public byte[] ary_email;
    }
}
