//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20090510151139
namespace KeelKit.Generators
{


    [Keel.ORM.DataViewAttribute("SPInfos", @"U0VMRUNUIA0Kc3BfbmFtZSA9T0JKUy5uYW1lICAsICANCnNwX3NxbCA9YXNtLmRlZmluaXRpb24gICAgLA0Kc3BfcG1pbmRleCA9UE0uW09SRElOQUxfUE9TSVRJT05dICAgICwNCnNwX3BhcmFtbmFtZT0gUE0uUEFSQU1FVEVSX05BTUUgLA0Kc3BfcG1kYXRhdHlwZSA9IFBNLkRBVEFfVFlQRSAgLA0Kc3BfcG1iaXRjb3VudD0gSVNOVUxMKFBNLkNIQVJBQ1RFUl9PQ1RFVF9MRU5HVEggLElTTlVMTChQTS5OVU1FUklDX1BSRUNJU0lPTixzYXAubWF4X2xlbmd0aCApKSwNCnNwX3BtbGVuZ2h0ID0gSVNOVUxMKFBNLkNIQVJBQ1RFUl9NQVhJTVVNX0xFTkdUSCAsSVNOVUxMKFBNLk5VTUVSSUNfUFJFQ0lTSU9OX1JBRElYICxzYXAucHJlY2lzaW9uKSksDQpzcF9wbXNjYWxlID0gc2FwLnNjYWxlICAgLA0Kc3BfcG1pc291dCA9UE0uSVNfUkVTVUxUICAgICwNCnNwX3BtbW9kPSBQTS5QQVJBTUVURVJfTU9ERSAgIA0KIA0KRlJPTSAgICAgICAgc3lzLmFsbF9vYmplY3RzIGFzIE9CSlMNCiAgam9pbiBbc3lzXS5bYWxsX3NxbF9tb2R1bGVzXSBhcyBhc20gb24gT0JKUy5vYmplY3RfaWQgPWFzbS5vYmplY3RfaWQgICANCiAgam9pbiAgSU5GT1JNQVRJT05fU0NIRU1BLlBBUkFNRVRFUlMgUE0gb24gUE0uU1BFQ0lGSUNfTkFNRSAgID1PQkpTLm5hbWUgDQogIGpvaW4gc3lzLmFsbF9wYXJhbWV0ZXJzIGFzIHNhcCBvbiAoc2FwLm9iamVjdF9pZCA9T0JKUy5vYmplY3RfaWQgYW5kIFBNLk9SRElOQUxfUE9TSVRJT04gPXNhcC5wYXJhbWV0ZXJfaWQgKQ0KIHdoZXJlIA0KIChPQkpTLnR5cGUgPSAnUCcgT1IgT0JKUy50eXBlID0gJ1gnIE9SIE9CSlMudHlwZSA9ICdQQycpIGFuZCBPQkpTLmlzX21zX3NoaXBwZWQgPSAwIA==")]
    public class SPInfos
    {

        private string _sp_name;

        private string _sp_sql;

        private int _sp_pmindex;

        private string _sp_paramname;

        private string _sp_pmdatatype;

        private int _sp_pmbitcount;

        private int _sp_pmlenght;

        private byte _sp_pmscale;

        private string _sp_pmisout;

        private string _sp_pmmod;

        [Keel.ORM.DataFieldAttribute("sp_name")]
        public string sp_name
        {
            get
            {
                return this._sp_name;
            }
            set
            {
                this._sp_name = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_sql")]
        public string sp_sql
        {
            get
            {
                return this._sp_sql;
            }
            set
            {
                this._sp_sql = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmindex")]
        public int sp_pmindex
        {
            get
            {
                return this._sp_pmindex;
            }
            set
            {
                this._sp_pmindex = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_paramname")]
        public string sp_paramname
        {
            get
            {
                return this._sp_paramname;
            }
            set
            {
                this._sp_paramname = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmdatatype")]
        public string sp_pmdatatype
        {
            get
            {
                return this._sp_pmdatatype;
            }
            set
            {
                this._sp_pmdatatype = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmbitcount")]
        public int sp_pmbitcount
        {
            get
            {
                return this._sp_pmbitcount;
            }
            set
            {
                this._sp_pmbitcount = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmlenght")]
        public int sp_pmlenght
        {
            get
            {
                return this._sp_pmlenght;
            }
            set
            {
                this._sp_pmlenght = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmscale")]
        public byte sp_pmscale
        {
            get
            {
                return this._sp_pmscale;
            }
            set
            {
                this._sp_pmscale = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmisout")]
        public string sp_pmisout
        {
            get
            {
                return this._sp_pmisout;
            }
            set
            {
                this._sp_pmisout = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("sp_pmmod")]
        public string sp_pmmod
        {
            get
            {
                return this._sp_pmmod;
            }
            set
            {
                this._sp_pmmod = value;
            }
        }
    }
}
