'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090508174134
Namespace Model
    
    <Keel.ORM.DataTableAttribute("tb_codfiles")>  _
    Public Class tb_codfiles
        
        Private _filemd5 As String
        
        Private _filepath As String
        
        <Keel.ORM.KeyFieldAttribute("filemd5", "String", false)>  _
        Public Property filemd5() As String
            Get
                Return Me._filemd5
            End Get
            Set
                Me._filemd5 = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("filepath", "String")>  _
        Public Property filepath() As String
            Get
                Return Me._filepath
            End Get
            Set
                Me._filepath = value
            End Set
        End Property
    End Class
End Namespace
