'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090508174134
Namespace Model
    
    <Keel.ORM.DataTableAttribute("tb_codsoftitem")>  _
    Public Class tb_codsoftitem
        
        Private _CodFileMd5 As String
        
        Private _FullName As String
        
        Private _SoftName As String
        
        Private _Version As String
        
        Private _Size As Integer
        
        Private _Created As Date
        
        Private _Score_Good As Integer
        
        Private _Score_Bad As Integer
        
        Private _Money As Integer
        
        Private _UploadDateTime As Date
        
        Private _PhoneTypes As String
        
        Private _PhoneOS As String
        
        <Keel.ORM.DataFieldAttribute("CodFileMd5", "String")>  _
        Public Property CodFileMd5() As String
            Get
                Return Me._CodFileMd5
            End Get
            Set
                Me._CodFileMd5 = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("FullName", "String")>  _
        Public Property FullName() As String
            Get
                Return Me._FullName
            End Get
            Set
                Me._FullName = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("SoftName", "String")>  _
        Public Property SoftName() As String
            Get
                Return Me._SoftName
            End Get
            Set
                Me._SoftName = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Version", "String")>  _
        Public Property Version() As String
            Get
                Return Me._Version
            End Get
            Set
                Me._Version = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Size", "Int32")>  _
        Public Property Size() As Integer
            Get
                Return Me._Size
            End Get
            Set
                Me._Size = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Created", "DateTime")>  _
        Public Property Created() As Date
            Get
                Return Me._Created
            End Get
            Set
                Me._Created = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Score_Good", "Int32")>  _
        Public Property Score_Good() As Integer
            Get
                Return Me._Score_Good
            End Get
            Set
                Me._Score_Good = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Score_Bad", "Int32")>  _
        Public Property Score_Bad() As Integer
            Get
                Return Me._Score_Bad
            End Get
            Set
                Me._Score_Bad = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("Money", "Int32")>  _
        Public Property Money() As Integer
            Get
                Return Me._Money
            End Get
            Set
                Me._Money = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("UploadDateTime", "DateTime")>  _
        Public Property UploadDateTime() As Date
            Get
                Return Me._UploadDateTime
            End Get
            Set
                Me._UploadDateTime = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("PhoneTypes", "String")>  _
        Public Property PhoneTypes() As String
            Get
                Return Me._PhoneTypes
            End Get
            Set
                Me._PhoneTypes = value
            End Set
        End Property
        
        <Keel.ORM.DataFieldAttribute("PhoneOS", "String")>  _
        Public Property PhoneOS() As String
            Get
                Return Me._PhoneOS
            End Get
            Set
                Me._PhoneOS = value
            End Set
        End Property
    End Class
End Namespace
