'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Keel.ORM
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Text

'生成日期:20090508174134
Namespace Model
    
    <Keel.ORM.DataTableAttribute("tb_user")>  _
    Public Class tb_user
        
        '''<summary>
        '''用户名
        '''</summary>
        Private _username As String
        
        '''<summary>
        '''密码
        '''</summary>
        Private _password As String
        
        '''<summary>
        '''手机类型
        '''</summary>
        Private _phonetype As String
        
        '''<summary>
        '''电邮
        '''</summary>
        Private _email As String
        
        '''<summary>
        '''用户名
        '''</summary>
        <Keel.ORM.DataFieldAttribute("username", "String")>  _
        Public Property username() As String
            Get
                Return Me._username
            End Get
            Set
                Me._username = value
            End Set
        End Property
        
        '''<summary>
        '''密码
        '''</summary>
        <Keel.ORM.DataFieldAttribute("password", "String")>  _
        Public Property password() As String
            Get
                Return Me._password
            End Get
            Set
                Me._password = value
            End Set
        End Property
        
        '''<summary>
        '''手机类型
        '''</summary>
        <Keel.ORM.DataFieldAttribute("phonetype", "String")>  _
        Public Property phonetype() As String
            Get
                Return Me._phonetype
            End Get
            Set
                Me._phonetype = value
            End Set
        End Property
        
        '''<summary>
        '''电邮
        '''</summary>
        <Keel.ORM.DataFieldAttribute("email", "String")>  _
        Public Property email() As String
            Get
                Return Me._email
            End Get
            Set
                Me._email = value
            End Set
        End Property
    End Class
End Namespace
