//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 生成日期:20081228222438
namespace KeelKit.Generators
{
    using System.Data;
    using Keel.ORM;


    [Keel.ORM.DataViewAttribute("SQLTableInfo", "U0VMRUNUIA0KdF90YWJsZW5hbWUgICAgICA9IENBU0UgV0hFTiBBLkNPTE9SREVSPTEgVEhFTiBELk5BT" +
        "UUgRUxTRSBELk5BTUUgRU5ELA0KdF90YWJsZWRlc2MgICAgPSBDQVNFIFdIRU4gQS5DT0xPUkRFUj0xI" +
        "FRIRU4gSVNOVUxMKEYuVkFMVUUsJycpIEVMU0UgJycgRU5ELA0KdF9maWVsZGluZGV4ICA9IEEuQ09MT" +
        "1JERVIsDQp0X2ZpZWxkbmFtZSAgICA9IEEuTkFNRSwNCnRfaWRlbnRpdHkgID0gQ0FTRSBXSEVOIENPT" +
        "FVNTlBST1BFUlRZKCBBLklELEEuTkFNRSwnSVNJREVOVElUWScpPTEgVEhFTiAnocwnRUxTRSAnJyBFT" +
        "kQsDQp0X3RhYmxla2V5ICAgICAgPSBDQVNFIFdIRU4gRVhJU1RTKFNFTEVDVCAxIEZST00gU1lTT0JKR" +
        "UNUUyBXSEVSRSBYVFlQRT0nUEsnIEFORCBQQVJFTlRfT0JKPUEuSUQgQU5EIE5BTUUgSU4gKA0KU0VMR" +
        "UNUIE5BTUUgRlJPTSBTWVNJTkRFWEVTIFdIRVJFIElORElEIElOKA0KU0VMRUNUIElORElEIEZST00gU" +
        "1lTSU5ERVhLRVlTIFdIRVJFIElEID0gQS5JRCBBTkQgQ09MSUQ9QS5DT0xJRCkpKSBUSEVOICehzCcgR" +
        "UxTRSAnJyBFTkQsDQp0X2ZpZWxkdHlwZSAgICAgID0gQi5OQU1FLA0KdF9maWVsZGJpdGNvdW50ID0gQ" +
        "S5MRU5HVEgsDQp0X2ZpZWxkbGVuZ2h0ICAgICA9IENPTFVNTlBST1BFUlRZKEEuSUQsQS5OQU1FLCdQU" +
        "kVDSVNJT04nKSwNCnRfZmllbGRzY2FsZSAgPSBJU05VTEwoQ09MVU1OUFJPUEVSVFkoQS5JRCxBLk5BT" +
        "UUsJ1NDQUxFJyksMCksDQp0X2ZpZWxkY2FubnVsbCAgID0gQ0FTRSBXSEVOIEEuSVNOVUxMQUJMRT0xI" +
        "FRIRU4gJ6HMJ0VMU0UgJycgRU5ELA0KdF9maWVsZGRlZmF1bHR2YWx1ZSAgICA9IElTTlVMTChFLlRFW" +
        "FQsJycpLA0KdF9maWVsZGRlc2MgID0gSVNOVUxMKEcuW1ZBTFVFXSwnJyksDQp0X2ZpZWxkaXNjb21wd" +
        "XRlZCA9Q0FTRSBXSEVOIEEuSVNDT01QVVRFRD0xIFRIRU4gJ6HMJ0VMU0UgJycgRU5EDQpGUk9NIA0KU" +
        "1lTQ09MVU1OUyBBDQpMRUZUIEpPSU4gDQpTWVNUWVBFUyBCIA0KT04gDQpBLlhVU0VSVFlQRT1CLlhVU" +
        "0VSVFlQRQ0KSU5ORVIgSk9JTiANClNZU09CSkVDVFMgRCANCk9OIA0KQS5JRD1ELklEICBBTkQgRC5YV" +
        "FlQRT0nVScgQU5EICBELk5BTUU8PidEVFBST1BFUlRJRVMnDQpMRUZUIEpPSU4gDQpTWVNDT01NRU5UU" +
        "yBFIA0KT04gDQpBLkNERUZBVUxUPUUuSUQNCkxFRlQgSk9JTiANCnN5cy5leHRlbmRlZF9wcm9wZXJ0a" +
        "WVzIEcgDQpPTiANCkEuSUQ9Ry5tYWpvcl9pZCBBTkQgQS5DT0xJRD1HLm1pbm9yX2lkICANCkxFRlQgS" +
        "k9JTiANCnN5cy5leHRlbmRlZF9wcm9wZXJ0aWVzIEYgDQpPTiANCkQuSUQ9Ri5tYWpvcl9pZCBBTkQgR" +
        "i5taW5vcl9pZD0wDQpPUkRFUiBCWSANCkEuSUQsQS5DT0xPUkRFUg==")]
    [DataView("ViewInfo","U0VMRUNUIA0KdF90YWJsZW5hbWUgICAgICA9IEMuVEFCTEVfTkFNRSAsDQp0X3RhYmxlZGVzYyAgICA9ICAnJywNCnRfZmllbGRpbmRleCAgPSAgQy5PUkRJTkFMX1BPU0lUSU9OICwNCnRfZmllbGRuYW1lICAgID0gQy5DT0xVTU5fTkFNRSAsDQp0X2lkZW50aXR5ICA9ICAnJyAgLA0KdF90YWJsZWtleSAgICAgID0gICcnLA0KdF9maWVsZHR5cGUgICAgICA9IEMuREFUQV9UWVBFICwNCnRfZmllbGRiaXRjb3VudCA9IElTTlVMTCAoIEMuQ0hBUkFDVEVSX09DVEVUX0xFTkdUSCxJU05VTEwoQy5OVU1FUklDX1BSRUNJU0lPTiwwKSApLA0KdF9maWVsZGxlbmdodCAgICAgPSAgSVNOVUxMKGMuQ0hBUkFDVEVSX01BWElNVU1fTEVOR1RILElTTlVMTChDLk5VTUVSSUNfUFJFQ0lTSU9OX1JBRElYICwwKSkgLA0KdF9maWVsZHNjYWxlICA9IElTTlVMTChDLk5VTUVSSUNfU0NBTEUsMCksDQp0X2ZpZWxkY2FubnVsbCAgID0gQ0FTRSBXSEVOIEMuSVNfTlVMTEFCTEUgPSdZRVMnIFRIRU4gJ6HMJ0VMU0UgJycgRU5ELA0KdF9maWVsZGRlZmF1bHR2YWx1ZSAgICA9IElTTlVMTChDLkNPTFVNTl9ERUZBVUxUICwnJyksDQp0X2ZpZWxkZGVzYyAgPSAgJycgLA0KdF9maWVsZGlzY29tcHV0ZWQgPSAnJyAgDQpGUk9NIA0KICAgSU5GT1JNQVRJT05fU0NIRU1BLkNPTFVNTlMgIGFzIEMsIElORk9STUFUSU9OX1NDSEVNQS5WSUVXUyBBUyBWIA0Kd2hlcmUNCg0KQy5UQUJMRV9OQU1FICA9IFYuVEFCTEVfTkFNRSAg")]
    [DataViewSQL("U0VMRUNUICBTRVJWRVJQUk9QRVJUWSgncHJvZHVjdHZlcnNpb24nKQ==", "OC4wMC4yMDM5", 
        "IFNFTEVDVCANCnRfdGFibGVuYW1lICAgICAgPSBDQVNFIFdIRU4gQS5DT0xPUkRFUj0xIFRIRU4gRC5OQ" +
        "U1FIEVMU0UgRC5OQU1FIEVORCwNCnRfdGFibGVkZXNjICAgID0gQ0FTRSBXSEVOIEEuQ09MT1JERVI9M" +
        "SBUSEVOIElTTlVMTChGLlZBTFVFLCcnKSBFTFNFICcnIEVORCwNCnRfZmllbGRpbmRleCAgPSBBLkNPT" +
        "E9SREVSLA0KdF9maWVsZG5hbWUgICAgPSBBLk5BTUUsDQp0X2lkZW50aXR5ICA9IENBU0UgV0hFTiBDT" +
        "0xVTU5QUk9QRVJUWSggQS5JRCxBLk5BTUUsJ0lTSURFTlRJVFknKT0xIFRIRU4gJ6HMJ0VMU0UgJycgR" +
        "U5ELA0KdF90YWJsZWtleSAgICAgID0gQ0FTRSBXSEVOIEVYSVNUUyhTRUxFQ1QgMSBGUk9NIFNZU09CS" +
        "kVDVFMgV0hFUkUgWFRZUEU9J1BLJyBBTkQgUEFSRU5UX09CSj1BLklEIEFORCBOQU1FIElOICgNClNFT" +
        "EVDVCBOQU1FIEZST00gU1lTSU5ERVhFUyBXSEVSRSBJTkRJRCBJTigNClNFTEVDVCBJTkRJRCBGUk9NI" +
        "FNZU0lOREVYS0VZUyBXSEVSRSBJRCA9IEEuSUQgQU5EIENPTElEPUEuQ09MSUQpKSkgVEhFTiAnocwnI" +
        "EVMU0UgJycgRU5ELA0KdF9maWVsZHR5cGUgICAgICA9IEIuTkFNRSwNCnRfZmllbGRiaXRjb3VudCA9I" +
        "EEuTEVOR1RILA0KdF9maWVsZGxlbmdodCAgICAgPSBDT0xVTU5QUk9QRVJUWShBLklELEEuTkFNRSwnU" +
        "FJFQ0lTSU9OJyksDQp0X2ZpZWxkc2NhbGUgID0gSVNOVUxMKENPTFVNTlBST1BFUlRZKEEuSUQsQS5OQ" +
        "U1FLCdTQ0FMRScpLDApLA0KdF9maWVsZGNhbm51bGwgICA9IENBU0UgV0hFTiBBLklTTlVMTEFCTEU9M" +
        "SBUSEVOICehzCdFTFNFICcnIEVORCwNCnRfZmllbGRkZWZhdWx0dmFsdWUgICAgPSBJU05VTEwoRS5UR" +
        "VhULCcnKSwNCnRfZmllbGRkZXNjICA9IElTTlVMTChHLltWQUxVRV0sJycpLA0KdF9maWVsZGlzY29tc" +
        "HV0ZWQgPUNBU0UgV0hFTiBBLklTQ09NUFVURUQ9MSBUSEVOICehzCdFTFNFICcnIEVORA0KRlJPTSANC" +
        "lNZU0NPTFVNTlMgQQ0KTEVGVCBKT0lOIA0KU1lTVFlQRVMgQiANCk9OIA0KQS5YVVNFUlRZUEU9Qi5YV" +
        "VNFUlRZUEUNCklOTkVSIEpPSU4gDQpTWVNPQkpFQ1RTIEQgDQpPTiANCkEuSUQ9RC5JRCAgQU5EIEQuW" +
        "FRZUEU9J1UnIEFORCAgRC5OQU1FPD4nRFRQUk9QRVJUSUVTJw0KTEVGVCBKT0lOIA0KU1lTQ09NTUVOV" +
        "FMgRSANCk9OIA0KQS5DREVGQVVMVD1FLklEDQpMRUZUIEpPSU4gICAgDQpzeXNwcm9wZXJ0aWVzICAgR" +
        "iAgIA0KT04NCmEuaWQgICA9ICAgZi5pZCAgIGFuZCAgIGEuY29saWQgICA9ICAgZi5zbWFsbGlkDQpMR" +
        "UZUIEpPSU4gICAgDQpzeXNwcm9wZXJ0aWVzICAgRyAgIA0KT04NCmQuaWQgICA9ICAgZy5pZCAgIGFuZ" +
        "CAgIGEuY29saWQgICA9ICAgZy5zbWFsbGlkIA0KT1JERVIgQlkgDQpBLklELEEuQ09MT1JERVINCg==")
        
        ]
    
    
    public class SQLTableInfo
    {

        private string _t_tablename;

        private string  _t_tabledesc;

        private int  _t_fieldindex;

        private string _t_fieldname;

        private string _t_identity;

        private string _t_tablekey;

        private string _t_fieldtype;

        private int  _t_fieldbitcount;

        private int _t_fieldlenght;

        private int _t_fieldscale;

        private string _t_fieldcannull;

        private string _t_fielddefaultvalue;

        private string  _t_fielddesc;

        private string _t_fieldiscomputed;

        [Keel.ORM.DataFieldAttribute("t_tablename")]
        public virtual string t_tablename
        {
            get
            {
                return this._t_tablename;
            }
            set
            {
                this._t_tablename = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_tabledesc")]
        public virtual string  t_tabledesc
        {
            get
            {
                return this._t_tabledesc;
            }
            set
            {
                this._t_tabledesc = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldindex")]
        public virtual int  t_fieldindex
        {
            get
            {
                return this._t_fieldindex;
            }
            set
            {
                this._t_fieldindex = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldname")]
        public virtual string t_fieldname
        {
            get
            {
                return this._t_fieldname;
            }
            set
            {
                this._t_fieldname = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_identity")]
        public virtual string t_identity
        {
            get
            {
                return this._t_identity;
            }
            set
            {
                this._t_identity = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_tablekey")]
        public virtual string t_tablekey
        {
            get
            {
                return this._t_tablekey;
            }
            set
            {
                this._t_tablekey = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldtype")]
        public virtual string t_fieldtype
        {
            get
            {
                return this._t_fieldtype;
            }
            set
            {
                this._t_fieldtype = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldbitcount")]
        public virtual int  t_fieldbitcount
        {
            get
            {
                return this._t_fieldbitcount;
            }
            set
            {
                this._t_fieldbitcount = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldlenght")]
        public virtual int t_fieldlenght
        {
            get
            {
                return this._t_fieldlenght;
            }
            set
            {
                this._t_fieldlenght = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldscale")]
        public virtual int t_fieldscale
        {
            get
            {
                return this._t_fieldscale;
            }
            set
            {
                this._t_fieldscale = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldcannull")]
        public virtual string t_fieldcannull
        {
            get
            {
                return this._t_fieldcannull;
            }
            set
            {
                this._t_fieldcannull = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fielddefaultvalue")]
        public virtual string t_fielddefaultvalue
        {
            get
            {
                return this._t_fielddefaultvalue;
            }
            set
            {
                this._t_fielddefaultvalue = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fielddesc")]
        public virtual string  t_fielddesc
        {
            get
            {
                return this._t_fielddesc;
            }
            set
            {
                this._t_fielddesc = value;
            }
        }

        [Keel.ORM.DataFieldAttribute("t_fieldiscomputed")]
        public virtual string t_fieldiscomputed
        {
            get
            {
                return this._t_fieldiscomputed;
            }
            set
            {
                this._t_fieldiscomputed = value;
            }
        }
    }
}
